---
abstract: 'Perl 6 - like grapheme level string handling'
author:
  - 'Moritz Lenz'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Str
provides:
  Perl6::Str:
    file: lib/Perl6/Str.pm
    version: v0.0.5
  Perl6::Str::Test:
    file: lib/Perl6/Str/Test.pm
    version: 0
requires:
  Encode: 0
  Test::More: 0
  Unicode::Normalize: 0
  charnames: 0
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.5
