---
name: Perl6-Str
version: 0.0.2
author:
  - Moritz Lenz
abstract: 'Perl 6 - like grapheme level string handling'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Encode: 0
  Test::More: 0
  Unicode::Normalize: 0
  charnames: 0
  perl: 5.008.001
provides:
  Perl6::Str:
    file: lib/Perl6/Str.pm
    version: 0.0.2
  Perl6::Str::Test:
    file: lib/Perl6/Str/Test.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
