---
abstract: 'Perl 6 - like grapheme level string handling'
author:
  - 'Moritz Lenz'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Str
provides:
  Perl6::Str:
    file: lib/Perl6/Str.pm
    version: v0.0.4
  Perl6::Str::Test:
    file: lib/Perl6/Str/Test.pm
requires:
  Encode: 0
  Test::More: 0
  Unicode::Normalize: 0
  charnames: 0
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.4
